apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configs.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - namespace
                - outputType
                - gitRef
                - kubeConfig
                - folderStructure
              properties:
                namespace:
                  type: string
                includeResource:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - apiVersion
                    properties:
                      name:
                        type: string
                      apiVersion:
                        type: string
                      withManagedFields:
                        type: boolean
                      withStatusField:
                        type: boolean
                excludeResource:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - apiVersion
                    properties:
                      name:
                        type: string
                      apiVersion:
                        type: string
                      withManagedFields:
                        type: boolean
                      withStatusField:
                        type: boolean
                labels:
                  type: object
                  additionalProperties:
                    type: string
                outputType:
                  type: string
                  enum:
                    - yaml
                    - json
                annotations:
                  type: object
                  additionalProperties:
                    type: string
                gitRef:
                  type: string
                kubeConfig:
                  type: string
                folderStructure:
                  type: string
  scope: Namespaced
  names:
    plural: configs
    singular: config
    kind: Config
    shortNames:
      - cfg
