apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - protocol
                - repositoryUrl
                - branch
                - repositoryPath
                - repositoryFolder
              properties:
                protocol:
                  type: string
                  enum:
                    - http
                    - https
                    - ssh
                repositoryUrl:
                  type: string
                  format: uri
                branch:
                  type: string
                username:
                  type: string
                password:
                  type: string
                sshPrivateKeyPath:
                  type: string
                repositoryPath:
                  type: string
                repositoryFolder:
                  type: string
                dryRun:
                  type: boolean
  scope: Namespaced
  names:
    plural: gitconfigs
    singular: gitconfig
    kind: GitConfig
    shortNames:
      - gitcfg
