---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - gitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - gitconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - versioning.k8sversioner.app
  resources:
  - gitconfigs/status
  verbs:
  - get
  - patch
  - update
